[package]
name = "identia"
version = "0.4.1"
description = "Decentralized, censorship resistant social media on IPFS"
authors = [ "iohzrd" ]
license = "AGPL-3.0"
repository = "https://github.com/iohzrd/tauri-svelte"
default-run = "identia"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.4", features = [] }

[dependencies]
chrono = { version = "0.4.19", features = [ "serde" ] }
common-multipart-rfc7578 = "0.3.1"
feed-rs = "1.0.0"
futures = "0.3.21"
infer = "0.7.0"
ipfs-api = { git = "https://github.com/iohzrd/rust-ipfs-api", features = [ "with-hyper" ] }
kamadak-exif = "0.5.4"
libp2p = { default-features = false, features = [ "identify", "noise" ], version = "0.43.0" }
qrcode = "0.12.0"
r2d2 = "0.8.9"
r2d2_sqlite = "0.20.0"
rusqlite = { version = "0.27.0", features = [ "bundled", "serde_json" ] }
rusqlite_migration = "0.5.1"
serde = { version = "1.0.136", features = [ "derive" ] }
serde_json = "1.0.79"
tauri = { version = "1.0.0-rc.4", features = ["api-all", "system-tray"] }
tokio = { version = "1.17.0", features = [ "full", "rt", "rt-multi-thread", "sync", "fs" ] }

[dependencies.libsignal-protocol]
git = "https://github.com/signalapp/libsignal-client"
tag = "v0.12.0"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
