[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
directories = "3.0.2"
futures = "0.3.16"
infer = "0.5.0"
ipfs-api = "0.11.0"
kamadak-exif = "0.5.4"
mime = "0.3.16"
qrcode = "0.12.0"
rusqlite = { version = "0.25.3", features = ["bundled", "serde_json"] }
rusqlite_migration = "0.4.2"
serde = { version = "1.0.128", features = ["derive"] }
serde_json = "1.0.66"
tauri = { version = "1.0.0-beta.8", features = ["api-all", "cli", "system-tray", "updater"] }
tokio = { version = "1.10", features = [ "full", "rt", "rt-multi-thread", "sync", "fs" ] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
