[package]
name = "identia"
version = "0.4.2"
description = "Decentralized, censorship resistant social media on IPFS"
authors = [ "iohzrd" ]
license = "AGPL-3.0"
repository = "https://github.com/iohzrd/tauri-svelte"
default-run = "identia"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.7", features = [] }

[dependencies]
feed-rs = "1.0"
ipfs-api = "0.15"
ipfs-api-backend-hyper = { version = "0.4", features = ["with-send-sync", "with-builder"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "1.0.0-rc.8", features = ["api-all", "gtk-tray", "system-tray"] }

[dependencies.tauri-plugin-sql]
git = "https://github.com/iohzrd/tauri-plugin-sql"
features = ["sqlite"]
branch = "dev"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
