[package]
name = "identia"
version = "0.4.30"
description = "Decentralized, censorship resistant social media on IPFS"
authors = [ "iohzrd" ]
license = "AGPL-3.0"
repository = "https://github.com/iohzrd/tauri-svelte"
default-run = "identia"
edition = "2021"
rust-version = "1.63"

[profile.release]
strip = true

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
feed-rs = "1"
ipfs-api-backend-hyper = { version = "0.4", features = ["with-send-sync"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "1", features = ["dialog-all", "fs-all", "http-all", "icon-png", "path-all", "shell-open", "shell-sidecar", "system-tray"] }
tauri-plugin-window-state = "0.1"
urlencoding = "2"

[dependencies.tauri-plugin-sql]
git = "https://github.com/iohzrd/tauri-plugin-sql"
features = ["sqlite"]
branch = "dev"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
