[package]
name = "Identia"
version = "0.1.0"
description = "Decentralized, censorship resistant social media on IPFS"
authors = ["iohzrd"]
license = "GPL-3.0"
repository = "https://github.com/iohzrd/tauri-svelte"
default-run = "Identia"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
common-multipart-rfc7578 = "0.3.0"
futures = "0.3.17"
infer = "0.5.0"
ipfs-api = { git = "https://github.com/iohzrd/rust-ipfs-api", features = ["with-hyper"] }
kamadak-exif = "0.5.4"
libp2p = { default-features = false, features = ["identify", "noise"], version = "0.39.1" }
mime = "0.3.16"
qrcode = "0.12.0"
r2d2 = "0.8.9"
r2d2_sqlite = "0.18.0"
rusqlite = { version = "0.25.3", features = ["bundled", "serde_json"] }
rusqlite_migration = "0.4.2"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
tauri = { version = "1.0.0-beta.8", features = ["api-all", "cli", "system-tray", "updater"] }
tokio = { version = "1.11.0", features = [ "full", "rt", "rt-multi-thread", "sync", "fs" ] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
