[package]
name = "identia"
version = "0.4.1"
description = "Decentralized, censorship resistant social media on IPFS"
authors = [ "iohzrd" ]
license = "AGPL-3.0"
repository = "https://github.com/iohzrd/tauri-svelte"
default-run = "identia"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.4", features = [] }

[dependencies]
chrono = { version = "0.4", features = [ "serde" ] }
futures = "0.3"
r2d2 = "0.8"
r2d2_sqlite = "0.20"
rusqlite = { version = "0.27", features = [ "bundled", "serde_json" ] }
rusqlite_migration = "0.5"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
tauri = { version = "1.0.0-rc.4", features = ["api-all", "system-tray"] }

[dependencies.ipfs-api]
git = "https://github.com/ferristseng/rust-ipfs-api"
features = ["with-hyper"]
branch = "master"

[dependencies.ipfs-api-backend-hyper]
git = "https://github.com/ferristseng/rust-ipfs-api"
features = ["with-send-sync"]
branch = "master"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
