[package]
name = "identia"
version = "0.4.0"
description = "Decentralized, censorship resistant social media on IPFS"
authors = [ "iohzrd" ]
license = "GPL-3.0"
repository = "https://github.com/iohzrd/tauri-svelte"
default-run = "identia"
edition = "2018"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
chrono = { version = "0.4.19", features = [ "serde" ] }
common-multipart-rfc7578 = "0.3.1"
feed-rs = "1.0.0"
futures = "0.3.18"
infer = "0.5.0"
ipfs-api = { git = "https://github.com/iohzrd/rust-ipfs-api", features = [ "with-hyper" ] }
kamadak-exif = "0.5.4"
libp2p = { default-features = false, features = [ "identify", "noise" ], version = "0.41.0" }
qrcode = "0.12.0"
r2d2 = "0.8.9"
r2d2_sqlite = "0.19.0"
rusqlite = { version = "0.26.3", features = [ "bundled", "serde_json" ] }
rusqlite_migration = "0.5.1"
serde = { version = "1.0.131", features = [ "derive" ] }
serde_json = "1.0.72"
tauri = { version = "1.0.0-beta.8", features = [ "api-all", "cli", "system-tray", "updater" ] }
tokio = { version = "1.14.0", features = [ "full", "rt", "rt-multi-thread", "sync", "fs" ] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
